# github.com/MadBomber/justprep/**/ruby/justfile
#

set positional-arguments := true

# List available recipes
@help:
  echo
  echo "Available Recipes at"
  echo `pwd`
  echo "are:"
  echo
  just -l --list-prefix 'just ' --list-heading ''
  echo

# Run the minitest examples on the Ruby code
test: build
  rake test


# Build the current gem
@build:
  rake clean clobber build


# Install the gem locally
@install:
  rake install:local

