# .../justprep/test/main.run

##
# see if the world is paying attention
world: hello what
  echo "world"

##
# Usage
my_help:
  echo
  run -l
  echo


# All sorts of interesting keywords
# from which to choose ...
#
# The parameter is a file name/path.  The path can be
# relative to the location of the main.just file OR it
# can be absolute (ie. starts with a / character).
# If the file does not exists and error message will
# be displayed to STDERR.

import one.run
include   two.run
require       three.run
with            four.run

# NOTE: no use of quotes around file name
require file with spaces.run

##
# where did those come from?
what: one two three four five six worked
  echo "what?"

#############################################
# Dose run have an alias concept?

# alias cr  := compile
# alias ins := install

##
# Compile the crystal version of justprep
compile:
  crystal build --no-debug --release -p -o bin/justprep justprep.cr

##
# Install the justprep executable in ~/bin
install: compile
  cp bin/justprep ~/bin
