# github.com/MadBomber/justprep/**/crystal/justfile
#
# brew install just
# Handy way to save and run project-specific commands
# https://github.com/casey/just
#

alias help := list

# List available recipes
@list:
  echo
  echo "Available Recipes at"
  echo `pwd`
  echo "are:"
  echo
  just -l --list-prefix 'just ' --list-heading ''
  echo


# Install the justprep executable in ~/bin
install where="/usr/local/bin": compile
  cp bin/justprep {{where}}


alias cr  := compile
alias ins := install

# Compile the crystal version of justprep
compile: make_bin
  crystal build --no-debug --release -p -o bin/justprep justprep.cr version.cr


# Create the ./bin directory if it does not exist
@make_bin:
  #!/bin/bash
  if [[ ! -d ./bin ]] ; then
    mkdir ./bin
  fi
